### ISSUE TITLE
Crash on file upload

### ISSUE THREAD

**Issue by pooki3bear** [moloch--/sliver-py#1]
I've bolted the code below into both examples `Automatically Interact With New Sessions (Async)`
, and `Automatically Interact With New Sessions (Threads)`  from https://github.com/moloch--/sliver-py/blob/master/docs/getting-started.rst

During the upload the implant crashes, and the timeout is eventually reached. 
```
interact = await client.interact(event.Session.ID)
file = open("myfile.exe", "rb")
fb = file.read()
ul = await interact.upload("testfile1234", fb, encoder='gzip')
```

**Comment by moloch--** [comment]
Possibly related to https://github.com/BishopFox/sliver/issues/380

**Comment by moloch--** [comment]
Fix in: https://github.com/BishopFox/sliver/pull/407
