### ISSUE TITLE
Broken/Missing sliver 1.5 support

### ISSUE THREAD

**Issue by cmprmsd** [moloch--/sliver-py#2]
It seems the client currently does not work with the current stage branch. 
The client does not expect a "token". This is the error with the "Event Example (Threads)" from your documentation.

```python
python3 sliver-notificationbot.py
Traceback (most recent call last):
  File "/root/sliver-notificationbot.py", line 29, in <module>
    main()
  File "/root/sliver-notificationbot.py", line 15, in main
    config = SliverClientConfig.parse_config_file(DEFAULT_CONFIG)
  File "/usr/local/lib/python3.9/dist-packages/sliver/config.py", line 78, in parse_config_file
    return cls.parse_config(data)
  File "/usr/local/lib/python3.9/dist-packages/sliver/config.py", line 65, in parse_config
    return cls(**json.loads(data))
TypeError: __init__() got an unexpected keyword argument 'token'
```

**Comment by moloch--** [comment]
Sliver v1.5 is not officially released yet, so no support yet. We'll update this library when we officially release v1.5

**Comment by cmprmsd** [comment]
Thanks for the heads up :) 
Looking forward to it!

**Comment by moloch--** [comment]
Initial v1.5 support is in `v0.0.15` and later, updated docs. I've removed the threaded client implementation as it was too much for me to maintain along with the asyncio versions, but you really should be using asyncio anways.

Not all v1.5 features are supported, but all the basics should be there.

**Comment by cmprmsd** [comment]
Thanks! I have to admit I quickly switched to the Go version in order to write the notification and conditional reaction bots. 🙂 

Thanks for writing the wiki entry "write your own client"! 😁 

Do you plan on offering some c2 training specifically on sliver? My company would certainly be interested.

**Comment by moloch--** [comment]
Bishop Fox doesn't really sell training, so no plans to do that sorry! I've spoken to some folks that do sell training, and it sounds like Sliver may be incorporated into a few trainings given by 3rd parties though!
