### ISSUE TITLE
Calling jobs returns error in client.py

### ISSUE THREAD

**Issue by DoctorEww** [moloch--/sliver-py#25]
**Describe the bug**
Calling jobs returns error in client.py

![image](https://user-images.githubusercontent.com/22088063/196046377-77043fe8-64ee-4f44-b529-e68e3b9169da.png)

**Comment by daddycocoaman** [comment]
Hi, this is being fixed in the next update.

**Comment by daddycocoaman** [comment]
The issue was that the protobuf had changed the jobs were under `Jobs.Active` not `Jobs.Jobs`. Fixed in v0.0.18.
